### PR TITLE
Fix compilation error on FreeBSD 12

### LINKED ISSUE #1539: v0.7.14 fails to compile with libc v0.2.110 on FreeBSD 12
```
error[E0063]: missing field `ext` in initializer of `kevent`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/unix/selector/kqueue.rs:56:9
    |
56  |         libc::kevent {
    |         ^^^^^^^^^^^^ missing `ext`
...
138 |             let kevent = kevent!(fd, libc::EVFILT_WRITE, flags, token.0);
    |                          ----------------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `kevent` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0063]: missing field `ext` in initializer of `kevent`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/unix/selector/kqueue.rs:56:9
    |
56  |         libc::kevent {
    |         ^^^^^^^^^^^^ missing `ext`
...
144 |             let kevent = kevent!(fd, libc::EVFILT_READ, flags, token.0);
    |                          ---------------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `kevent` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0063]: missing field `ext` in initializer of `kevent`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/unix/selector/kqueue.rs:56:9
    |
56  |         libc::kevent {
    |         ^^^^^^^^^^^^ missing `ext`
...
183 |             kevent!(fd, libc::EVFILT_WRITE, write_flags, token.0),
    |             ----------------------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `kevent` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0063]: missing field `ext` in initializer of `kevent`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/unix/selector/kqueue.rs:56:9
    |
56  |         libc::kevent {
    |         ^^^^^^^^^^^^ missing `ext`
...
184 |             kevent!(fd, libc::EVFILT_READ, read_flags, token.0),
    |             --------------------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `kevent` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0063]: missing field `ext` in initializer of `kevent`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/unix/selector/kqueue.rs:56:9
    |
56  |         libc::kevent {
    |         ^^^^^^^^^^^^ missing `ext`
...
205 |             kevent!(fd, libc::EVFILT_WRITE, flags, 0),
    |             ----------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `kevent` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0063]: missing field `ext` in initializer of `kevent`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/unix/selector/kqueue.rs:56:9
    |
56  |         libc::kevent {
    |         ^^^^^^^^^^^^ missing `ext`
...
206 |             kevent!(fd, libc::EVFILT_READ, flags, 0),
    |             ---------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `kevent` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0063]: missing field `ext` in initializer of `kevent`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/unix/selector/kqueue.rs:56:9
    |
56  |           libc::kevent {
    |           ^^^^^^^^^^^^ missing `ext`
...
226 |           let mut kevent = kevent!(
    |  __________________________-
227 | |             0,
228 | |             libc::EVFILT_USER,
229 | |             libc::EV_ADD | libc::EV_CLEAR | libc::EV_RECEIPT,
230 | |             token.0
231 | |         );
    | |_________- in this macro invocation
    |
    = note: this error originates in the macro `kevent` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0063]: missing field `ext` in initializer of `kevent`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.14/src/sys/unix/selector/kqueue.rs:56:9
    |
56  |           libc::kevent {
    |           ^^^^^^^^^^^^ missing `ext`
...
245 |           let mut kevent = kevent!(
    |  __________________________-
246 | |             0,
247 | |             libc::EVFILT_USER,
248 | |             libc::EV_ADD | libc::EV_RECEIPT,
249 | |             token.0
250 | |         );
    | |_________- in this macro invocation
    |
    = note: this error originates in the macro `kevent` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0063`.
error: could not compile `mio` due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

1. `kevent` definition in libc crate for FreeBSD 12: https://github.com/rust-lang/libc/blob/6b9d5099d103df9b076778d97c3607b2ed2729a9/src/unix/bsd/freebsdlike/freebsd/freebsd12/mod.rs#L20-L28
2. CI failure: https://cirrus-ci.com/task/5565875227983872?logs=build#L78

### PR DESCRIPTION
**Pull request by messense**
Fixes #1539 

Needs to backport to v0.7.x

### CODE REVIEW

**Comment by messense** [comment]
```
running 2 tests
test lio::smoke ... FAILED
test aio::smoke ... FAILED
```

Looks like these two tests are flaky, a rerun fixed them.

**Comment by asomers** [comment]
This is a libc bug.  Fixing it here: https://github.com/rust-lang/libc/pull/2585

**Comment by messense** [comment]
> This is a libc bug. Fixing it here: [rust-lang/libc#2585](https://github.com/rust-lang/libc/pull/2585)

Great! I'll close this one.
