### ISSUE TITLE
Failure to find Poll::new on Windows

### ISSUE THREAD

**Issue by masp** [tokio-rs/mio#1338]
Trying to compile the simple example below fails to compile on version `0.7.0`, but works on version `0.6.7`. The error message I get is that `Poll::new` is not a valid function and cannot be found:

```
error[E0599]: no function or associated item named `new` found for struct `mio::poll::Poll` in the current scope
  --> src\main.rs:10:22
   |
10 |     let poll = Poll::new()?;
   |                      ^^^ function or associated item not found in `mio::poll::Poll`

error: aborting due to previous error
```

Looking at the code, it looks like it's behind a cfg flag that prevents it from being defined on Windows.

OS: Windows 10
Rust version: 1.46.0
Code:
```rust
use mio::{Events, Poll, Token, Interest};
use std::net::TcpListener;
use std::time::Duration;
use std::io;
use std::io::Error;

const SERVER: Token = Token(0);

fn main() -> Result<(), Error> {
    let poll = Poll::new()?;
    let mut events = Events::with_capacity(128);

    let address = "127.0.0.1:25565".parse()?;
    let mut listener = TcpListener::bind(address)?;
    poll.registry().register(&mut listener, SERVER, Interest::READABLE)?;

    loop {
        poll.poll(&mut events, Some(Duration::from_millis(100)))?;

        for event in events.iter() {
            match event.token() {
                SERVER => loop {
                    match listener.accept() {
                        Ok((connection, address)) => {
                            println!("Got a connection from: {}", address);
                        }
                        Err(ref err) if would_block(err) => break,
                        Err(err) => return Err(err)
                    }
                }
            }
        }
    }
}

fn would_block(err: &io::Error) -> bool {
    err.kind() == io::ErrorKind::WouldBlock
}
```

**Comment by masp** [comment]
In case someone is foolish like me, I forgot the `features = ["os-poll", "tcp"]` note in the example.
